### ISSUE TITLE
ValueError: cannot determine region size; use 4-item box

### ISSUE THREAD

**Issue by lccsetsun** [cvondrick/vatic#115]
Highlighting 2 tracks...
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 5, in <module>
    pkg_resources.run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 16, in <module>
    turkic.cli.main()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 147, in main
    handler(args[1:])
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 47, in __init__
    self(parser.parse_args(args))
  File "/home/vagrant/vatic/cli.py", line 494, in __call__
    lambda x: "{0}/{1}.jpg".format(args.output, x))
  File "/usr/local/lib/python2.7/dist-packages/pyvision-0.3.1-py2.7-linux-x86_64.egg/vision/visualize.py", line 115, in save
    for image, frame in images:
  File "/home/vagrant/vatic/cli.py", line 497, in renumber
    for count, (im, _) in enumerate(it):
  File "/home/vagrant/vatic/cli.py", line 504, in augment
    aug.paste("black")
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 1331, in paste
ValueError: cannot determine region size; use 4-item box

**Comment by lccsetsun** [comment]
turkic visualize job_id /home/images/job_id  --merge --renumber.Use the above command to report errors as above

**Comment by lccsetsun** [comment]
My goal is to export the same image number as JSON number, because now the exported image number starts from 0001.jpg and the JSON file content starts from 0, which bothers me a lot.

**Comment by EnnaSachdeva** [comment]
Did you fix this?
I'm also getting the same error while virtualizing the annotated images.
