### ISSUE TITLE
turkic setup --database question

### ISSUE THREAD

**Issue by tjusxh** [cvondrick/vatic#22]
When I run turkic setup --database
It occurs:
vipa@VIPA:~/software/vatic$ turkic setup --database
/usr/lib/python2.7/dist-packages/pkg_resources.py:1049: UserWarning: /home/vipa/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 4, in <module>
    __import__('pkg_resources').run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 16, in <module>
    turkic.cli.main()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 147, in main
    handler(args[1:])
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 47, in __init__
    self(parser.parse_args(args))
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 470, in __call__
    self.database(args)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 455, in database
    database.install()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/database.py", line 45, in install
    Base.metadata.create_all(engine)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 3614, in create_all
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1842, in _run_visitor
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1835, in _optional_conn_ctx_manager
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 2026, in contextual_connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 2065, in _wrap_pool_connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1395, in _handle_dbapi_exception_noconnection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 2061, in _wrap_pool_connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 337, in connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 644, in _checkout
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 439, in checkout
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 964, in _do_get
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 961, in _do_get
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 284, in _create_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 410, in __init__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 538, in __connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/strategies.py", line 89, in connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 377, in connect
  File "build/bdist.linux-x86_64/egg/MySQLdb/__init__.py", line 81, in Connect
    
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 187, in __init__
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by tjusxh** [comment]
change the password about mysql.

**Comment by pammirato** [comment]
how did you resolve this?
