### ISSUE TITLE
question about frame extraction

### ISSUE THREAD

**Issue by tjusxh** [cvondrick/vatic#23]
$ turkic status --verify
Testing acess to database server... ok
Testing acess to web server... ok
but  Frame Extraction 
 $ mkdir /path/to/output/directory
 $ turkic extract /path/to/video.mp4 /path/to/output/directory
question as follows,please help me.
/usr/lib/python2.7/dist-packages/pkg_resources.py:1049: UserWarning: /home/vipa/.python-eggs is writable by group/others and vulnerable to attack when used with get_reame. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
ffmpeg version 2.5.git Copyright (c) 2000-2015 the FFmpeg developers
  built on Feb  1 2015 00:26:45 with gcc 4.9.1 (Ubuntu 4.9.1-16ubuntu6)
  configuration: --enable-gpl --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libx264 --enable-nonfree --enable-x11grab --enable-shared --enable-pi
  libavutil      54. 18.100 / 54. 18.100
  libavcodec     56. 21.101 / 56. 21.101
  libavformat    56. 19.100 / 56. 19.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.  9.102 /  5.  9.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/vipa/software/vatic/1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2014-07-07 09:02:18
    location-zho    : +30.2613+120.1166/
    location        : +30.2613+120.1166/
  Duration: 00:00:15.62, start: 0.000000, bitrate: 4990 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 63 kb/s (default)
    Metadata:
      creation_time   : 2014-07-07 09:02:18
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 4921 kb/s, 30.03 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2014-07-07 09:02:18
      handler_name    : Core Media Video
Please use -b:a or -b:v, -b is ambiguous
[swscaler @ 0x197c360] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/tmp/pyvision-ffmpeg-33363523/%d.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    location        : +30.2613+120.1166/
    location-zho    : +30.2613+120.1166/
    encoder         : Lavf56.19.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1280x720, q=2-31, 10000 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2014-07-07 09:02:18
      handler_name    : Core Media Video
      encoder         : Lavc56.21.101 mjpeg
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
frame=  469 fps=128 q=24.8 Lsize=N/A time=00:00:15.64 bitrate=N/A    
video:25518kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Decoding frames 0 to 100
Aborted. Cleaning up...
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 4, in <module>
    __import__('pkg_resources').run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 16, in <module>
    turkic.cli.main()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 147, in main
    handler(args[1:])
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 47, in __init__
    self(parser.parse_args(args))
  File "/home/vipa/software/vatic/cli.py", line 53, in __call__
    image.thumbnail((args.width, args.height), Image.BILINEAR)
  File "/usr/local/lib/python2.7/dist-packages/PIL-1.1.7-py2.7-linux-x86_64.egg/Image.py", line 1559, in thumbnail
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL-1.1.7-py2.7-linux-x86_64.egg/ImageFile.py", line 189, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL-1.1.7-py2.7-linux-x86_64.egg/Image.py", line 385, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder jpeg not available

**Comment by mbakthav** [comment]
probably you dont have libjpeg

**Comment by tjusxh** [comment]
@mbakthav  I check my system！
sudo apt-get install -y git python-setuptools python-dev libavcodec-dev libavformat-dev libswscale-dev libjpeg62 libjpeg62-dev libfreetype6 libfreetype6-dev apache2 libapache2-mod-wsgi mysql-server-5.1 mysql-client-5.1 libmysqlclient-dev gfortran 
all of package are updated. But my system use 
mysql-server-core-5.5 mysql-server-5.5 mysql-server-core-5.5:i386 mysql-server-5.5:i386 replace mysql-server-core-5.1
I only download setuptools (15.1).Others are same with you.
Requirement already satisfied (use --upgrade to upgrade): cython==0.20 in /usr/local/lib/python2.7/dist-packages
munkres 1.0.7 is already the active version in easy-install.pth
MySQL-python 1.2.5 is already the active version in easy-install.pth
numpy 1.9.2 is already the active version in easy-install.pth
parsedatetime 1.4 is already the active version in easy-install.pth
PIL 1.1.7 is already the active version in easy-install.pth
Finished processing dependencies for pyvision==0.3.1
Finished processing dependencies for pip==6.1.1
SQLAlchemy 1.0.0 is already the active version in easy-install.pth
Finished processing dependencies for turkic==0.2.5
wsgilog 0.3 is already the active version in easy-install.pth
But rather the same error as mentioned above.

**Comment by FridayJK** [comment]
i also meet this problem, and the requirement list on the vatic-install.sh is satisfied. I used mysql-server-5.7 and mysql-client-5.7 to instead original version. Have you solved this problem?
