### ISSUE TITLE
ImportError: No module named vision

### ISSUE THREAD

**Issue by wizard00** [cvondrick/vatic#29]
This might be a noob question but after I setup apache2 and sql following README, I tried turkic command in vatic directory.

But no matter I try turkic setup --dabatase or turkic publish --offline or any turkic command
All I got is this same error:
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 5, in <module>
    pkg_resources.run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 12, in <module>
    import cli
  File "/home/yufeiw/VATIC/vatic/cli.py", line 11, in <module>
    from vision import Box
ImportError: No module named vision

I am a newbie for python, but I think the code is looking file vision.
Therefore I tried to copy vision from pyvision to vatic. It worked HOWEVER I run into another importError:
File "/home/yufeiw/VATIC/vatic/vision/\__init\__.py", line 1, in <module>
    from annotations import *
ImportError: No module named annotations
(I do find file annotations.pyx in the folder though)

It seems like moving files around is not the correct approach.
What did I do wrong? and What should I do? Thanks

**Comment by psychosane** [comment]
I am facing the exact same issue. Anyone has an idea?

**Comment by yhzyhzyhz** [comment]
I am also facing the same issue. and I tried to install pyvision using : 

$python setup.py build
$sudo python setup.py install

nothing happend, and I tried to run python in the pyvision folder, when import vision, it has the same problem of no module named annotations.

**Comment by yhzyhzyhz** [comment]
I tried this

https://github.com/cvondrick/vatic/issues/16

after using cython 0.20 it seems working and installed pyvision successfuly.

**Comment by iraadit** [comment]
As said by @yhzyhzyhz, it works when installing cython 0.20 then rebuilding and installing pyvision

```
sudo pip install cython==0.20
cd pyvision
sudo python setup.py build
sudo python setup.py install
```

**Comment by hukangrong** [comment]
@iraadit I installed vision successful!

> Installed /usr/local/lib/python2.7/dist-packages/pyvision-0.3.1-py2.7-linux-x86_64.egg
> Processing dependencies for pyvision==0.3.1
> Finished processing dependencies for pyvision==0.3.1
But it's still worry!

> import vision
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "vision/__init__.py", line 1, in <module>
>     from annotations import *
> ImportError: No module named annotations

**Comment by mjcorriere** [comment]
I am having the same issue trying to install Vatic. No module named vision

**Comment by BhargavaRamM** [comment]
@hukangrong were you able to solve the issue you had with **ImportError: No module named annotations**? I have the same issue and I see the problem is due to missing annotations.py file.

**Comment by hukangrong** [comment]
@BhargavaRamM do you know what you need to use in your project? In my project, I skip this problem by compiling "features.pyx" and importing features model in my project. So I don't fix this problem.

**Comment by BhargavaRamM** [comment]
@hukangrong I did the same thing you did. I compiled annotations.pyx file to create annotations.so. This resolved the ImportError. Thanks.

**Comment by evgenykam** [comment]
@hukangrong I am having the same issue trying to install Vatic. How do you compiled annotation.pyx? Can you share your commands? Thanks

**Comment by AloshkaD** [comment]
Same thing here, ImportError: No module named vision.

**Comment by hukangrong** [comment]
@evgenykam Sorry for too late to response. I give you the example of compiling features model.
`cython -a features.pyx
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing \
      -I/usr/include/python2.7 -o features.so features.c`
