### ISSUE TITLE
Turkic setup error

### ISSUE THREAD

**Issue by athus1990** [cvondrick/vatic#33]
While installing,such that in 000-default file I have given    
Local domain name being "athmuntu"
 DocumentRoot /var/www/vatic
 ScriptAlias /server /var/www/vatic/server.py
AddHandler cgi-script .cgi .pl .py

And in config.py file:
localhost   = "http://athmuntu" # your local host
database    = "mysql://root:pass@athmuntu/vatic"

sudo turkic setup --database throws an error:
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 5, in <module>
    pkg_resources.run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
.
.
.
.
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on 'athmuntu' (111)")

**Comment by drewm1980** [comment]
is "pass" actually what you set for the root database user? This is usually set during install.

Maybe also try 

> database = "mysql://root:pass@localhost/vatic"

?

I am new to database setup; take my response with a grain of salt!
