### ISSUE TITLE
Vatic in offline mode

### ISSUE THREAD

**Issue by ming8924** [cvondrick/vatic#38]
Hi,
I have just got vatic to work in offline mode and am able to annotate the video segments. However, when I type ```turkic list --published``` it shows nothing. ```turkic list --stats``` shows 0/30 completed videos even though I have annotated some videos and save the work.

Also, I am wondering for the offline mode, do I have to enter the url every time I work on a video segments?

Thanks

**Comment by qgicup** [comment]
Have the same problem here as well :-(

**Comment by Jamesjue** [comment]
After digging into the code, I found the solution. In the object box shown as below, there is a check mark on the top right corner. After clicking that and click "save work" button, your video will be marked as done.

![screenshot from 2016-04-13 21 53 54](https://cloud.githubusercontent.com/assets/1829669/14514812/02a667da-01c2-11e6-9708-14156e40f3ed.png)

For your second question, please see my answer in [https://github.com/cvondrick/vatic/issues/24#issuecomment-209677162](url)

**Comment by gsikheria** [comment]
Hi @Jamesjue,

This check mark in object box, I'm not able to find in --offline mode. Is this online mode.? I want to track user in  --offline mode. Is this possible.

![](https://cloud.githubusercontent.com/assets/1829669/14514812/02a667da-01c2-11e6-9708-14156e40f3ed.png)

**Comment by Jamesjue** [comment]
I'm running offline mode. You need to create an object first by clicking the add button, and then you'll see it

**Comment by gsikheria** [comment]
@Jamesjue , I'm also running in offline mode but I'm not able to see id, classify button, Tracking etc. Have you done any changes in code
![vvv](https://cloud.githubusercontent.com/assets/8925234/15065024/98b846a4-1378-11e6-8f4e-b443c7d63cca.png)

**Comment by Jamesjue** [comment]
A more well-maintained fork of vatic is here: https://github.com/johndoherty/vatic

**Comment by ymm8505** [comment]
/home/vatic/pyvision
vatic@ubuntu:~/pyvision$ sudo python setup.py install
building liblinear
make: Entering directory `/home/vatic/pyvision/vision/liblinear'
g++ -Wall -Wconversion -O2 -fPIC -c -o tron.o tron.cpp
g++ -Wall -Wconversion -O2 -fPIC -c -o linear.o linear.cpp
linear.cpp: In function ‘model* load_model(const char*)’:
linear.cpp:1832:24: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fp,"%80s",cmd);
                        ^
linear.cpp:1835:25: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp,"%80s",cmd);
                         ^
linear.cpp:1855:29: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp,"%d",&nr_class);
                             ^
linear.cpp:1860:31: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp,"%d",&nr_feature);
                               ^
linear.cpp:1865:26: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp,"%lf",&bias);
                          ^
linear.cpp:1877:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf(fp,"%d",&model_->label[i]);
                                      ^
linear.cpp:1904:44: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp, "%lf ", &model_->w[i*nr_w+j]);
                                            ^
linear.cpp:1905:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fp, "\n");
                   ^
make -C blas OPTFLAGS='-Wall -Wconversion -O2 -fPIC' CC='cc';
make[1]: Entering directory `/home/vatic/pyvision/vision/liblinear/blas'
cc -Wall -Wconversion -O2 -fPIC  -c dnrm2.c
cc -Wall -Wconversion -O2 -fPIC  -c daxpy.c
cc -Wall -Wconversion -O2 -fPIC  -c ddot.c
cc -Wall -Wconversion -O2 -fPIC  -c dscal.c
ar rcv blas.a dnrm2.o daxpy.o ddot.o dscal.o   
a - dnrm2.o
a - daxpy.o
a - ddot.o
a - dscal.o
ranlib  blas.a
make[1]: Leaving directory `/home/vatic/pyvision/vision/liblinear/blas'
g++ -Wall -Wconversion -O2 -fPIC -o train train.c tron.o linear.o blas/blas.a
g++ -Wall -Wconversion -O2 -fPIC -o predict predict.c tron.o linear.o blas/blas.a
make: Leaving directory `/home/vatic/pyvision/vision/liblinear'
running install
running bdist_egg
running egg_info
creating pyvision.egg-info
writing pyvision.egg-info/PKG-INFO
writing top-level names to pyvision.egg-info/top_level.txt
writing dependency_links to pyvision.egg-info/dependency_links.txt
writing manifest file 'pyvision.egg-info/SOURCES.txt'
reading manifest file 'pyvision.egg-info/SOURCES.txt'
writing manifest file 'pyvision.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/vision
copying vision/cluster.py -> build/lib.linux-x86_64-2.7/vision
copying vision/pascal.py -> build/lib.linux-x86_64-2.7/vision
copying vision/visualize.py -> build/lib.linux-x86_64-2.7/vision
copying vision/__init__.py -> build/lib.linux-x86_64-2.7/vision
copying vision/drawer.py -> build/lib.linux-x86_64-2.7/vision
copying vision/autoreload.py -> build/lib.linux-x86_64-2.7/vision
copying vision/frameiterators.py -> build/lib.linux-x86_64-2.7/vision
copying vision/toymaker.py -> build/lib.linux-x86_64-2.7/vision
copying vision/detectionreader.py -> build/lib.linux-x86_64-2.7/vision
copying vision/flickr.py -> build/lib.linux-x86_64-2.7/vision
copying vision/ffmpeg.py -> build/lib.linux-x86_64-2.7/vision
creating build/lib.linux-x86_64-2.7/vision/track
copying vision/track/interpolation.py -> build/lib.linux-x86_64-2.7/vision/track
copying vision/track/__init__.py -> build/lib.linux-x86_64-2.7/vision/track
copying vision/track/util.py -> build/lib.linux-x86_64-2.7/vision/track
creating build/lib.linux-x86_64-2.7/vision/alearn
copying vision/alearn/__init__.py -> build/lib.linux-x86_64-2.7/vision/alearn
creating build/lib.linux-x86_64-2.7/vision/reporting
copying vision/reporting/__init__.py -> build/lib.linux-x86_64-2.7/vision/reporting
copying vision/reporting/track.py -> build/lib.linux-x86_64-2.7/vision/reporting
creating build/lib.linux-x86_64-2.7/vision/reconstruction
copying vision/reconstruction/__init__.py -> build/lib.linux-x86_64-2.7/vision/reconstruction
copying vision/reconstruction/plywriter.py -> build/lib.linux-x86_64-2.7/vision/reconstruction
copying vision/reconstruction/pmvs.py -> build/lib.linux-x86_64-2.7/vision/reconstruction
copying vision/reconstruction/bundler.py -> build/lib.linux-x86_64-2.7/vision/reconstruction
running build_ext
cythoning vision/annotations.pyx to vision/annotations.c
Traceback (most recent call last):
  File "setup.py", line 70, in <module>   ext_modules = ext_modules,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup   dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 88, in do_egg_install    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 185, in run    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 171, in call_command    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 21, in run    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 164, in run    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run  self.build_extensions()
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 171, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 324, in cython_sources
    full_module_name=module_name)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 682, in compile
    return compile_single(source, options, full_module_name)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 635, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 492, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Pipeline.py", line 365, in run_pipeline
    data = phase(data)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 131, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 359, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 435, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 435, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 4635, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 435, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 3067, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 1944, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 1698, in generate_function_body
    self.body.generate_execution_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 441, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 4785, in generate_execution_code
    self.generate_rhs_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 5072, in generate_rhs_evaluation_code
    self.rhs.generate_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 699, in generate_evaluation_code
    self.generate_subexpr_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 714, in generate_subexpr_evaluation_code
    node.generate_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 10498, in generate_evaluation_code
    super(NumBinopNode, self).generate_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 699, in generate_evaluation_code
    self.generate_subexpr_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 714, in generate_subexpr_evaluation_code
    node.generate_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 699, in generate_evaluation_code
    self.generate_subexpr_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 714, in generate_subexpr_evaluation_code
    node.generate_evaluation_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 705, in generate_evaluation_code
    self.generate_result_code(code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24-py2.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 3737, in generate_result_code
    self.type, self.base.type)
AssertionError: unexpected type long and base type tuple object for indexing

谁遇到过这样的报错？  帮忙解答一下谢谢~

**Comment by gsikheria** [comment]
Thanks @Jamesjue

**Comment by ymm8505** [comment]
@OmarMAmin  Try This 

cp    /home/vatic/turkic/turkic/public/*     /home/vatic/vatic/public/turkic

Then  Restart apache2

sudo apache2ctl graceful

**Comment by gsikheria** [comment]
@OmarMAmin  

Local host should be be define in 000-default.conf and config.py like
localhost = "http://localhost"

**Comment by OmarMAmin** [comment]
Thank you so much, it fixes the issue, i got the following:

  Localhost:   http://localhost

Testing access to Amazon Mechanical Turk... ERROR! Signature or access key missing
Testing access to database server... OK
Testing access to web server... ERROR! HTTP Error 403: Forbidden


and i tried the following 
https://github.com/cvondrick/vatic/issues/17#issuecomment-203003980

and it fixed the issue and now i'm trying to use it.

Thanks all for your help

**Comment by gsikheria** [comment]
Hi @Jamesjue 

As you have already install this version https://github.com/johndoherty/vatic  of vatic.  I'm facing some error. When it is comes to 

cd vatic_tracking
python setup.py install

running install
running build
running build_py
running build_ext
building 'cpptrack' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/etruser/anaconda2/include/python2.7 -c cpptrack/cpptrack.cpp -o build/temp.linux-x86_64-2.7/cpptrack/cpptrack.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/etruser/anaconda2/include/python2.7 -c cpptrack/trackingmodule.cpp -o build/temp.linux-x86_64-2.7/cpptrack/trackingmodule.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/etruser/anaconda2/include/python2.7 -c cpptrack/CompressiveTracker.cpp -o build/temp.linux-x86_64-2.7/cpptrack/CompressiveTracker.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/etruser/anaconda2/include/python2.7 -c cpptrack/CompressiveTrackerModule.cpp -o build/temp.linux-x86_64-2.7/cpptrack/CompressiveTrackerModule.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cpptrack/CompressiveTrackerModule.cpp:5:40: error: ‘string’ has not been declared
 void compressivetrack(Rect initialBox, string basePath,
                                        ^
cpptrack/CompressiveTrackerModule.cpp: In function ‘void compressivetrack(cv::Rect, int, int, int, std::vector<cv::Rect_<int> >&)’:
cpptrack/CompressiveTrackerModule.cpp:11:42: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
     getFrame(start, basePath, gray, false);
                                          ^
In file included from /usr/include/c++/4.8/string:53:0,
                 from /usr/local/include/opencv2/core/cvstd.hpp:58,
                 from /usr/local/include/opencv2/core/base.hpp:56,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/opencv.hpp:46,
                 from cpptrack/trackingmodule.h:1,
                 from cpptrack/CompressiveTrackerModule.cpp:1:
/usr/include/c++/4.8/bits/basic_string.tcc:212:5: error:   initializing argument 1 of ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ [-fpermissive]
     basic_string<_CharT, _Traits, _Alloc>::
     ^
cpptrack/CompressiveTrackerModule.cpp:17:42: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
         getFrame(i, basePath, gray, false);
                                          ^
In file included from /usr/include/c++/4.8/string:53:0,
                 from /usr/local/include/opencv2/core/cvstd.hpp:58,
                 from /usr/local/include/opencv2/core/base.hpp:56,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/opencv.hpp:46,
                 from cpptrack/trackingmodule.h:1,
                 from cpptrack/CompressiveTrackerModule.cpp:1:
/usr/include/c++/4.8/bits/basic_string.tcc:212:5: error:   initializing argument 1 of ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ [-fpermissive]
     basic_string<_CharT, _Traits, _Alloc>::
     ^
error: command 'gcc' failed with exit status 1

I'd be very thankful if you can help

**Comment by OmarMAmin** [comment]
the problem in the file CompressiveTrackerModule.cpp in vatir

you need to change string into std::string
and it'll compile with you

please let me know if you managed to get it working, as i couldn't, i'm stuck in the next step

**Comment by Jamesjue** [comment]
@gsikheria I didn't encounter any problem compiling the module. I compiled it on ubuntu 14.04 with gcc 4.8.4 and cython -0.24

**Comment by gsikheria** [comment]
Hi @OmarMAmin , Thanks for help. I 'm able to compile now. For #42 Cross check all  the packages  by going into shell script "vatic-install-local.sh". Try to install each packages separately, then again run the script.

**Comment by gsikheria** [comment]
Hi @Jamesjue and @ming8924 , 

Since my above problem is solved but I stuck at "turkic setup --database"

Traceback (most recent call last):
  File "/home/etruser/.env/bin/turkic", line 4, in <module>
    __import__('pkg_resources').run_script('turkic==0.2.5', 'turkic')
  File "/home/etruser/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/etruser/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/etruser/.env/lib/python2.7/site-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 12, in <module>
    import cli
  File "/home/etruser/vatic/cli.py", line 7, in <module>
    from turkic.cli import handler, importparser, Command, LoadCommand
  File "/home/etruser/.env/local/lib/python2.7/site-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 9, in <module>
    import database
  File "/home/etruser/.env/local/lib/python2.7/site-packages/turkic-0.2.5-py2.7.egg/turkic/database.py", line 30, in <module>
    engine = create_engine(config.database, pool_recycle = 3600)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/__init__.py", line 386, in create_engine
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/strategies.py", line 75, in create
  File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/mysql/mysqldb.py", line 92, in dbapi
ImportError: No module named MySQLdb

I've crossed checked I've  python-mysqldb, sqlalchemy.

**Comment by mobooya** [comment]
Hi @gsikheria , im getting the same error "ImportError no module named mysql.db" How did you resolve it?  Thanks

**Comment by gsikheria** [comment]
try  this
apt-get install python-mysqldb. If this not work  check , sqlalchemy.

**Comment by mobooya** [comment]
Thank you!

**Comment by OtkuPjnOz** [comment]
@ming8924 can you explain how did you make vatic work in offline mode...

I am running this command  

Turkic publish --offline

and there are links in the results but when I open those links it is not opening the GUI of vatic

**Comment by AkarshNKolekar** [comment]
Yep, even I'm not able to open the GUI for vatic after publishing it offline. How do we access the GUI? The link generated after `turkic publish --offline` gives a link like http://localhost?id=4&hitId=offline, but when i click on that, it shows "Server Error" on a black-grey screen.

**Comment by OtkuPjnOz** [comment]
@AkarshNKolekar  when I used the steps given in one of the answers of issue #37 for installation it resolved my problem
