### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/pyvision-ffmpeg-392218974/1.jpg'

### ISSUE THREAD

**Issue by mid9blues** [cvondrick/vatic#71]
I followed this install instruction page to setup VATIC
[http://qiita.com/jh3rox/items/8a83f4000146c3c887e9](http://qiita.com/jh3rox/items/8a83f4000146c3c887e9)

However, there is an issue happend when I try to run "turkic extract":
`$turkic extract ~/video/01.mp4 ~/video/output/` 

> sh: 1: avconv: not found
Aborted. Cleaning up...
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 4, in <module>
    __import__('pkg_resources').run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 16, in <module>
    turkic.cli.main()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 147, in main
    handler(args[1:])
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 47, in __init__
    self(parser.parse_args(args))
  File "/home/ubuntu/vatic-tool/vatic/cli.py", line 48, in __call__
    for frame, image in enumerate(sequence):
  File "/usr/local/lib/python2.7/dist-packages/pyvision-0.3.1-py2.7-linux-x86_64.egg/vision/ffmpeg.py", line 67, in __iter__
    yield self[i]
  File "/usr/local/lib/python2.7/dist-packages/pyvision-0.3.1-py2.7-linux-x86_64.egg/vision/ffmpeg.py", line 53, in __getitem__
    return Image.open(self.getframepath(k))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2258, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/tmp/pyvision-ffmpeg-392218974/1.jpg'

**Comment by mid9blues** [comment]
The problem is "sh: 1: avconv: not found".

It is solved after installing libav-tools
`sudo apt-get install libav-tools`

**Comment by hongjo** [comment]
Thank you. I had the same problem, solved by your suggestion.

**Comment by Yoga49** [comment]
Unable to locate package libbav-tools, so I  solved after installing libav-tools
`sudo apt-get install ffmpeg`
